services:
  postgres:
    environment:
      POSTGRES_DB: bibliflow_ci
      POSTGRES_USER: bibliflow_user
      POSTGRES_PASSWORD: ci_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bibliflow_user -d bibliflow_ci"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  backend:
    environment:
      NODE_ENV: test
      DATABASE_URL: postgresql://bibliflow_user:ci_password@postgres:5432/bibliflow_ci
      JWT_SECRET: ci-test-secret
    # Pas de volumes en CI (code figé dans l'image)
    command: npm run start:prod

  frontend:
    environment:
      NODE_ENV: production
      API_URL: http://backend:3000/api/v1
    # Pas de volumes en CI
    command: npm start

  # Désactiver les services non nécessaires en CI
  jenkins:
    profiles: ["disabled"]

  sonarqube:
    profiles: ["disabled"]
