version: '3.8'

services:
  backend-dev:
    volumes:
      - /workspace/biblioflow/biblioflow-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=ci
      - DATABASE_SYNCHRONIZE=true
      - DATABASE_LOGGING=false

  frontend-dev:
    volumes:
      - /workspace/biblioflow/biblioflow-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=ci
    ports:
      - "4201:4200"  # Changer le port pour éviter les conflits

  postgres:
    environment:
      - POSTGRES_DB=biblioflow_ci
    volumes:
      - postgres_ci_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro

  # Désactiver les services qui créent des conflits de ports
  frontend-prod:
    profiles:
      - disabled

  backend-prod:
    profiles:
      - disabled

  nginx:
    profiles:
      - disabled

volumes:
  postgres_ci_data:
